### ISSUE TITLE
aria2 设置之后不保存

### ISSUE THREAD

**Issue by conmor** [666wcy/pikpakdown#3]
https://files.catbox.moe/5mpg4l.jpg

https://files.catbox.moe/15ntbn.jpg

https://files.catbox.moe/5n84co.jpg

每次开都得重新设置一遍

**Comment by conmor** [comment]
https://files.catbox.moe/vo20mk.jpg

**Comment by conmor** [comment]
还有个问题，离线下载刷新动画那卡住的，只能重开一次，设置那可以加个不显示动画的按钮

**Comment by 666wcy** [comment]
1.下载列表的aria2不需要你进行设置
2.双击动画可取消加载
